# Generated by Django 6.0.3 on 2026-03-11 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testing',
            name='created_at',
        ),
    ]
